### ISSUE TITLE
same as posthtml-uglify ?

### ISSUE THREAD

**Issue by stevenvachon** [simonlc/posthtml-minify-classnames#1]
[posthtml-uglify](https://www.npmjs.com/package/posthtml-uglify)

How is this module different?

**Comment by simonlc** [comment]
Hmm, I haven't had the time to look at that module, but from looking at the readme it seems to start with two letter identifiers rather than one. Minify classnames also allows you to feed your own generator function, so you can make it generate any type of class names you want.

Another feature that may be unique is the minification of svg xlink:href ids used in "svg sprites".

Its worth looking ito both, but it looks like uglify has had a bit more development, so if theres more features i guess it just lacks the documentation.

**Comment by stevenvachon** [comment]
Thank you.
